Todo/urls.py
from django.conf.urls import patterns, url
from Todo.views import TodoList, TodoDetail, TodoCreate, TodoDelete, TodoUpdate

urlpatterns = patterns('todo.views',
    url(r'^$', TodoList.as_view(), name='todo_list'),
    url(r'^Todo(?P<pk>\d+)$', TodoDetail.as_view(), name='todo_detail'),
    url(r'^New$', TodoCreate.as_view(), name='todo_create'),
    url(r'^Todo(?P<pk>\d+)/Update$', TodoUpdate.as_view(), name='todo_update'),
    url(r'^Todo(?P<pk>\d+)/Delete$', TodoDelete.as_view(), name='todo_delete'),
)

movie_project/movie_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from MovieLib.views import IndexView,CreateView,CreateViewMixin,UpdateView,DeleteView
from Todo import views

from FileSample import views
from django.contrib import messages

# Los siguientes ficheros son para manejar los ficheros subidos al server.!!! 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'movie_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    # url(r'^movies/', include('MovieLib.urls')),
    # url(r'^TodoList/', include('Todo.urls')),
    url(r'^SAISA/', include('FileSample.urls')),
	# url(r'^$', include('FileSample.urls')),
	# url(r'^$', IndexView.as_view(), name='movie_index'),
	# url(r'^create$', CreateView.as_view(), name='movie_create'),
	# url(r'^createMixin$', CreateViewMixin.as_view(), name='movie_createMixin'),
	# url(r'^edit/(?P<pk>\d+)$', UpdateView.as_view(), name='movie_edit'),
	# url(r'^delete/(?P<pk>\d+)$', DeleteView.as_view(), name='movie_delete'),
    # url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
    # urlpatterns += patterns('',
        # url(r'^SAISA/(?P<path>.*)$', 'django.views.static.serve', {
            # 'document_root': settings.MEDIA_ROOT,
        # }),
   # )

movie_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from MovieLib.views import IndexView,CreateView,CreateViewMixin,UpdateView,DeleteView
from Todo import views

from FileSample import views
from django.contrib import messages

# Los siguientes ficheros son para manejar los ficheros subidos al server.!!! 
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'movie_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    # url(r'^movies/', include('MovieLib.urls')),
    # url(r'^TodoList/', include('Todo.urls')),
    url(r'^SAISA/', include('FileSample.urls')),
	# url(r'^$', include('FileSample.urls')),
	# url(r'^$', IndexView.as_view(), name='movie_index'),
	# url(r'^create$', CreateView.as_view(), name='movie_create'),
	# url(r'^createMixin$', CreateViewMixin.as_view(), name='movie_createMixin'),
	# url(r'^edit/(?P<pk>\d+)$', UpdateView.as_view(), name='movie_edit'),
	# url(r'^delete/(?P<pk>\d+)$', DeleteView.as_view(), name='movie_delete'),
    # url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
)
#+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# if settings.DEBUG:
    # urlpatterns += patterns('',
        # url(r'^SAISA/(?P<path>.*)$', 'django.views.static.serve', {
            # 'document_root': settings.MEDIA_ROOT,
        # }),
   # )

Todo/models.py
from django.db import models
from django.contrib.auth.models import User
#from myauth.models import User

# Create your models here.

class Todo(models.Model):
    PRIORITY_LIST = (
        (0, 'Low'),
        (5, 'Normal'),
        (10, 'High'),
        (15, 'Urgent'),
    )
    title = models.CharField(max_length=140)
    owner = models.ForeignKey(User)
    priority = models.PositiveSmallIntegerField(choices=PRIORITY_LIST, default=5)
    added_on = models.DateTimeField(auto_now_add=True)
    due_on = models.DateField()
    class Meta:
        permissions = (('view_todo', 'Can view todo'),)
        ordering = ['due_on']
    def __unicode__(self):
        return u"%s" % self.title
    @models.permalink
    def get_absolute_url(self):
        return ('todo_detail', [int(self.pk)])

templates/TodoApp/create.html
{% extends "base_page.html" %}
{% load url from future %}

{% block title %}Todo Form{% endblock %}

{% block content %}
<h3>{% if object %}Updating {{object}}{% else %}Add a new Todo{% endif %}</h3>
{% load crispy_forms_tags %}

<!--<form action="" method="post">{% csrf_token %}
<table>
{{ form|crispy }}
</table>-->
<!--<input type="submit" value="Save Todo"/>-->
<!--</form>-->

<div class="well">
	<form class="form-horizontal" action="" method="post">
		{% csrf_token %}
    	{% crispy form %}
    </form>
</div>

{% endblock %}

templates/TodoApp/delete_confirm.html
{% extends "base_page.html" %}
{% load url from future %}

{% block title %}{{object_name}} Confirm delete?{% endblock %}

{% block content %}
<h3>Are you sure you want to delete "{{object.title}}" Todo item?</h3>
<form action="" method="post">{% csrf_token %}
<input class="btn btn-primary" type="submit" value="Yes!"/>  
<input class="btn btn-primary" type="button" value="No..." onclick="window.history.go(-1);"/>
</form>
{% endblock %}

templates/TodoApp/details.html
{% extends "base_page.html" %}

{% block title %}{{todo.title}}{% endblock %}

{% block content %}
<table>
<tr><th>Title:</th><td>{{todo.title}}</td></tr>
<tr><th>Owner:</th><td>{{todo.owner}}</td></tr>
<tr><th>Priority:</th><td>{{todo.get_priority_display}}</td></tr>
<tr><th>Added on:</th><td>{{todo.added_on}}</td></tr>
<tr><th>Due on:</th><td>{{todo.due_on}}</td></tr>
</table>
	{% if perms.todo.change_todo %}
	<a href="{% url 'todo_update' todo.pk %}">Update</a>
	{% endif %} | {% if perms.todo.delete_todo %}
	<a href="{% url 'todo_delete' todo.pk %}">Delete</a>
	<div style="float:left">
        <button class="btn btn-primary" id="edit-todo" type="submit">Edit todo</button>
        <button class="btn btn-primary" id="delete-todo" type="submit">Delete todo</button>
    </div>
	{% endif %}
{% endblock %}

templates/TodoApp/todo_list.html
{% extends "base_page.html" %}

{% block title %}Todo List{% endblock %}

{% block content %}
<div class="table-responsive"> 
<table id="todoListItemsTable" class="table table-striped table-hover table-condensed">
<thead>
		<tr>
			<th>Title</th>
			<th>Priority</th>
			<th>Due on</th>
			<th>Action</th>
		</tr>
</thead>
<tbody>
  {% for todo in TodoList %}
  <tr>
	<td>{% if perms.todo.view_todo %}
		<a href="{{todo.get_absolute_url}}">{{todo.title}}</a>
		{% else %}
			{{todo.title}}
		{% endif %}
	</td>
	<td><ul id="{{todo.id}}"></ul>{{todo.priority}}</td>
	<td>{{todo.due_on}}</td>
	<td>{% if perms.todo.change_todo %}
		<a href="{% url 'todo_update' todo.pk %}">Update</a>
		{% endif %} | {% if perms.todo.delete_todo %}
		<a href="{% url 'todo_delete' todo.pk %}">Delete</a>{% endif %}
	</td>
  </tr>
  {% endfor %}
</tbody>
</table>
</div>
<div style="float:right">
            <button class="btn btn-primary" id="edit-todo" type="submit">Edit todo</button>
            <button class="btn btn-primary" id="delete-todo" type="submit">Delete todo</button>
</div>

<script type="text/javascript">
   $(function() {
    var url;
    var ItemId;
    $("#edit-todo").attr('disabled','disabled');
    $("#delete-todo").attr('disabled','disabled');

    $('#todoListItemsTable tr').click(function() 
    {
        ItemId = $(this).find("ul").attr("id");
        url = "{% url 'todo_update' 12345 %}".replace(/12345/, ItemId);
        $("#edit-todo").attr('disabled',false);
        $("#delete-todo").attr('disabled',false);
    });

    $('#edit-todo').click(function() 
    {
        //alert(url);
        url = "{% url 'todo_update' 12345 %}".replace(/12345/, ItemId);
        window.location = url;
    });

    $('#delete-todo').click(function() 
    {
        //alert(url);
        url = "{% url 'todo_delete' 12345 %}".replace(/12345/, ItemId);
        window.location = url;
    });

});
</script>

{% endblock %}